function validateData(x, functionName, argName, argIndex)
% Validate input data
validateattributes( ...
    x, ...
    {'numeric', 'logical'}, ...
    {'real'}, ...
    functionName, ...
    argName, ...
    argIndex)
end