function isValid = validateNumBins(numBins, functionName, argIndex)
% Validate numBins input argument
validateattributes( ...
    numBins , ...
    {'numeric'}, ...
    {'vector', 'nonempty', 'positive', 'integer', 'finite', '>', 0}, ...
    functionName, ...
    'numBins', ...
    argIndex)
isValid = numel(numBins) <= 2;
end